spring:
  profiles: default
  thymeleaf:
          prefix : classpath:/thymeleafTemplates/
          suffix : .html
          cache : false
  freemarker:
      template-loader-path: classpath:/templates/
      prefer-file-system-access: false
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hanseungsoo/InterfaceConfig.git
        prefix: /configration-registry
server:
  port: 8080
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/